### ISSUE TITLE
Multi Edit is possible

### ISSUE THREAD

**Issue by shyam2027** [GigaTables/reactables#55]
Hi dude, I done the Changes in Tools.js  active={(selectedRows.length !== 1) ? false : true} so popup is showing for when we select more than 1 and click edit but it fetching first selected data and its updating for first select data please help me on this

**Comment by arthurkushman** [comment]
1st of all - STOP creating issues, just because U need faster reaction. 
2nd, U didn't starred yet my plug-in neither contribute in any way  and demand a large amount of time.
3d U can't edit multiple rows, U can only delete multiple rows with Gigatables, or set the real-time edit with editableCells: true

U R welcome

**Comment by arthurkushman** [comment]
Also, U should recognize the fact, that U can't change the code, because of next versions support, which will tear Your previous version.
